<?php

namespace Database\Seeders;

use App\Models\ProductImage;
use Illuminate\Database\Seeder;

class ProductImageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        ProductImage::insert([
            [
                'id' => 1,
                'product_id' => '1',
                'name' => 'may-phat-2-chan-matiz_1517829888.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'product_id' => '2',
                'name' => 'may-phat-3giac-morning_1517826126.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'product_id' => '3',
                'name' => 'may-phat-6pk-2chan-forte-1_1517830134.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'product_id' => '4',
                'name' => 'may-phat-6pk-4chan-laceti_1517830762.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'product_id' => '5',
                'name' => 'may-phat-dien-6pk-tucson_1517840929.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'product_id' => '6',
                'name' => 'bi-may-o-truoc-hiace_1517311845.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'product_id' => '7',
                'name' => 'bi-moay-o-hilux-2012_1517308683.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'product_id' => '8',
                'name' => 'tong-phanh-abs-kia-morning_1517391286.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'product_id' => '9',
                'name' => 'bi-may-o-sau-getz_1517309287.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'product_id' => '10',
                'name' => 'phot-lai-santafe_1516898747.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'product_id' => '11',
                'name' => 'day-con-kia-newmorning_1516898151.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'product_id' => '12',
                'name' => 'bite-kia-morning_1516897603.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'product_id' => '13',
                'name' => 'bit-mazda-323_1516897136.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'product_id' => '14',
                'name' => 'bi-tr-gentra_1516896375.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'product_id' => '15',
                'name' => 'rotuyn-cang-a-van-morning_1516890965.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 16,
                'product_id' => '16',
                'name' => 'can-bang-nhua-cdx_1516889997.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'product_id' => '17',
                'name' => 'thanh-can-bang-getz_1516889784.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 18,
                'product_id' => '18',
                'name' => 'thanh-can-bang-truoc-cx5_1516881345.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 19,
                'product_id' => '19',
                'name' => 'can-bang-truoc-vios_1516881069.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 20,
                'product_id' => '20',
                'name' => 'thanh-can-bang-truoc-vena_1516880812.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // SAN PHẢM PHU TUNG THAN VO
            [
                'id' => 21,
                'product_id' => '21',
                'name' => 'moto-nang-kinh-trai-santafe_1517671379.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 22,
                'product_id' => '22',
                'name' => 'mo-to-nang-kinh-trai-forte_1517671216.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 23,
                'product_id' => '23',
                'name' => 'moto-nang-kinh-sau-trai-gentra_1517670968.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 24,
                'product_id' => '24',
                'name' => 'mo-to-nang-kinh-gentra_1517670748.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 25,
                'product_id' => '25',
                'name' => 'mo-to-nang-kinh-sau-phai-morning_1517670283.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 26,
                'product_id' => '26',
                'name' => 'mo-to-nang-kinh-trai-forte_1517671216.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 27,
                'product_id' => '27',
                'name' => 'moto-nang-kinh-sau-trai-gentra_1517670968.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 28,
                'product_id' => '28',
                'name' => 'mo-to-nang-kinh-gentra_1517670748.jpg    ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 29,
                'product_id' => '29',
                'name' => 'mo-to-nang-kinh-6-giac-kia-morning_1517651955.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 30,
                'product_id' => '30',
                'name' => 'moto-nang-kinh-truoc-trai_1517651624.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 31,
                'product_id' => '31',
                'name' => 'han-che-canh-cua-matiz_1517396818.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 32,
                'product_id' => '32',
                'name' => 'tai-cai-tai-xe-morning_1517396539.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 33,
                'product_id' => '33',
                'name' => 'tay-mo-cua-ngoai-matiz-2_1517396188.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 34,
                'product_id' => '34',
                'name' => 'tay-mo-cua-ngoai-gentra_1517396008.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 35,
                'product_id' => '35',
                'name' => 'tay-mo-cua-trong-getz_1517395696.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 36,
                'product_id' => '36',
                'name' => 'op-mat-calang-do-kieu-trd_1516006728.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 37,
                'product_id' => '37',
                'name' => 'ca-lang-camry-2010_1514911213.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 38,
                'product_id' => '38',
                'name' => 'mat-ca-lang-cheverlet-aveo-2008_1514904499.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 39,
                'product_id' => '39',
                'name' => 'mat-ca-lang-toyota-fortunner_1514904161.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 40,
                'product_id' => '40',
                'name' => '51117044116_1514285258.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // PHU TUNG DIEN, DH
            [
                'id' => 41,
                'product_id' => '41',
                'name' => 'loc-dieu-hoa-may-xang-10pa17c-carens-2012-20-977011d100-2_1529753933.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 42,
                'product_id' => '42',
                'name' => 'loc-dieu-hoa-elantra-i30-avante-976062h040_1529752505.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 43,
                'product_id' => '43',
                'name' => 'loc-dieu-hoa-hs15-4pk-sonata-ef-977012c100-hcc_1529683085.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 44,
                'product_id' => '44',
                'name' => 'loc-dieu-hoa-may-dau-carens-20-977011d200_1529667418.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 45,
                'product_id' => '45',
                'name' => 'loc-dieu-hoa-7pk-fortuner_1529576136.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 46,
                'product_id' => '46',
                'name' => 'loc-dieu-hoa-rio-2015-977011w600-doowon-3_1529511558.jpg ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 47,
                'product_id' => '47',
                'name' => 'loc-dieu-hoa-bt50-ranger-2015_1529504136.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 48,
                'product_id' => '48',
                'name' => 'loc-dieu-hoa-creta-2016-97701a6701-hcc_1529485321.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 49,
                'product_id' => '49',
                'name' => 'loc-dieu-hoa-camry-2014_1529403503.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 50,
                'product_id' => '50',
                'name' => 'mo-to-quat-ket-nuoc-getz-11_1528885360.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);
    }
}
